#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include <windows.h>
#include <time.h>
#include <pthread.h>



int main(){



}





/*
int main(){
	
	char relleno = 219;
	
	system("COLOR 0a");
	printf("Pulsa intro para emezar.");
	getchar();
	
	Beep(725,75 );
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    NO   IMAGE    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    CONNECTING    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   --   --   --   |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  ---  ---  ---  -|\n");
	printf("\t\t\t    |     CONNECTING   |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-  ---  ---  ---  |\n");
	printf("\t\t\t    |      CONNECTING  |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | --   --   --   --|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   ---  ---  ---|\n");
	printf("\t\t\t    |       CONNECTING |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t     ------------------\n");														  
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Beep(975,100);
	Beep(975,150);
	Sleep(700);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(500);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   | O    O   |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(200);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |   O    O |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(900);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O __ O  |   |\n");
	printf("\t\t\t    |   |   |  |   |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(1000);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |   |__|   |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(1000);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Hello, little duck.\n\n\n");
	Sleep(2500);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- You have grown very fast.\n\n\n");
	Sleep(2000);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- But by now, you have became a high rank soldier\n\n\t\t       on pidgeon's army.\n\n\n");
	Sleep(2500);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    --So, you have been sent to L.1. during the D day.\n\n\n");
	Sleep(2000);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Your orders are so simply. Survive and try to\n\n\t\t       deploy the troops behind the enemy.\n\n\n");
	Sleep(2800);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- ...\n\n\n");
	Sleep(2500);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     Q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Good Luck.\n\n\n");
	Sleep(2500);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(500);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  _    _  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  _    _  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Herr General, Over and out.\n\n\n");
	Sleep(1800);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	Beep(975,150);
	Beep(720, 150);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    NO   IMAGE    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   --   --   --   |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  ---  ---  ---  -|\n");
	printf("\t\t\t    |   NO   IMAGE     |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-  ---  ---  ---  |\n");
	printf("\t\t\t    |  NO   IMAGE      |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | --   --   --   --|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   ---  ---  ---|\n");
	printf("\t\t\t    | NO   IMAGE       |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("Ya esta");
	getch();
	return 0;
	}

//	printf("- Good Luck.\n\n\n- Herr General, Over and out.\n\n");
//	Beep(975,150);
//	Beep(720, 150);
//	Sleep(2000);
//	printf("\nPress any key to continue.\t");
	


/*int main(){
	int i=1;
	
	time_t start_t, end_t;
	
	double diff_t,old_t,new_t;
	time(&start_t);
	while(i){
		
		time(&end_t);
		
		diff_t = difftime(end_t,start_t);
		old_t=(diff_t-1);
		new_t=diff_t;
		printf("TIME : %f\n",diff_t);
		if(old_t==0){
			printf("\n\t[ %.0f - %.0f ] = %d\n", old_t, new_t, i);
			system("PAUSE");
			return 0;
		}
		i++;
	}
}
*/
/*
int main(){
	
	int metros=1000;
	int score=567098;
	int vidas=2;
	int misilTotal=0;
	
	char relleno = 219;
	char nombreSoldado[]="Manuel";

	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                                       {\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(1200);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("||\n");
	printf("||\n");
	printf("||                                      {\n");
	printf("||\n");
	printf("||\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\\\n");
	printf("| |\n");
	printf("| |\n");
	printf("| |                                     {\n");
	printf("| |\n");
	printf("| |\n");
	printf("|/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|_\n");
	printf("| \\\n");
	printf("|_ |\n");
	printf("|  |\n");
	printf("|  |                                    {\n");
	printf("|  |\n");
	printf("|\\ |\n");
	printf("|_/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|__\n");
	printf("|  \\\n");
	printf("|__ |\n");
	printf("|   |\n");
	printf("|   |                                   {\n");
	printf("|\\  |\n");
	printf("|_\\ |\n");
	printf("|__/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|___\n");
	printf("|   \\\n");
	printf("|___ |\n");
	printf("|    |\n");
	printf("|    |                                  {\n");
	printf("| \\  |\n");
	printf("|__\\ |\n");
	printf("|___/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|____\n");
	printf("|    \\\n");
	printf("|____ |\n");
	printf("|     |\n");
	printf("|\\    |                                 {\n");
	printf("|  \\  |\n");
	printf("|___\\ |\n");
	printf("|____/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|_____\n");
	printf("|     \\\n");
	printf("|_____ |\n");
	printf("|\\     |\n");
	printf("| \\    |                                {\n");
	printf("|   \\  |\n");
	printf("|____\\ |\n");
	printf("|_____/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|______\n");
	printf("|      \\\n");
	printf("| _____ |\n");
	printf("| \\     |\n");
	printf("|  \\    |                               {\n");
	printf("|    \\  |\n");
	printf("| ____\\ |\n");
	printf("|______/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|_______\n");
	printf("|       \\\n");
	printf("|  _____ |\n");
	printf("|  \\     |\n");
	printf("||  \\    |                              {\n");
	printf("||    \\  |\n");
	printf("|  ____\\ |\n");
	printf("|_______/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|________\n");
	printf("|_       \\\n");
	printf("|   _____ |\n");
	printf("|_  \\     |\n");
	printf("| |  \\    |                             {\n");
	printf("|_|    \\  |\n");
	printf("|   ____\\ |\n");
	printf("|________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|_________\n");
	printf("|__       \\\n");
	printf("|    _____ |\n");
	printf("|__  \\     |\n");
	printf("|  |  \\    |                            {\n");
	printf("|__|    \\  |\n");
	printf("|    ____\\ |\n");
	printf("|_________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|__________\n");
	printf("|___       \\\n");
	printf("|     _____ |\n");
	printf("|___  \\     |\n");
	printf("|   |  \\    |                           {\n");
	printf("|___|    \\  |\n");
	printf("|     ____\\ |\n");
	printf("|__________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|___________\n");
	printf("| ___       \\\n");
	printf("||     _____ |\n");
	printf("||___  \\     |\n");
	printf("|    |  \\    |                          {\n");
	printf("| ___|    \\  |\n");
	printf("|      ____\\ |\n");
	printf("|___________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|____________\n");
	printf("|  ___       \\\n");
	printf("| |     _____ |\n");
	printf("| |___  \\     |\n");
	printf("|     |  \\    |                         {\n");
	printf("|  ___|    \\  |\n");
	printf("|       ____\\ |\n");
	printf("|____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
	system("cls");
	printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("| ____________\n");
	printf("|/  ___       \\\n");
	printf("|| |     _____ |\n");
	printf("|| |___  \\     |\n");
	printf("||     |  \\    |                        {\n");
	printf("||  ___|    \\  |\n");
	printf("||       ____\\ |\n");
	printf("|\\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("cls");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|  ____________\n");
	printf("| /  ___       \\\n");
	printf("| | |     _____ |\n");
	printf("| | |___  \\     |\n");
	printf("| |     |  \\    |                       {\n");
	printf("| |  ___|    \\  |\n");
	printf("| |       ____\\ |\n");
	printf("| \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|   ____________\n");
	printf("|  /  ___       \\\n");
	printf("|  | |     _____ |\n");
	printf("|  | |___  \\     |\n");
	printf("|  |     |  \\    |                      {\n");
	printf("|  |  ___|    \\  |\n");
	printf("|  |       ____\\ |\n");
	printf("|  \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|    ____________\n");
	printf("|   /  ___       \\\n");
	printf("|   | |     _____ |\n");
	printf("|   | |___  \\     |\n");
	printf("|   |     |  \\    |                     {\n");
	printf("|   |  ___|    \\  |\n");
	printf("|   |       ____\\ |\n");
	printf("|   \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|     ____________\n");
	printf("|    /  ___       \\\n");
	printf("|    | |     _____ |\n");
	printf("|    | |___  \\     |\n");
	printf("|    |     |  \\    |                    {\n");
	printf("|    |  ___|    \\  |\n");
	printf("|    |       ____\\ |\n");
	printf("|    \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|      ____________\n");
	printf("|     /  ___       \\\n");
	printf("|     | |     _____ |\n");
	printf("|     | |___  \\     |\n");
	printf("|     |     |  \\    |                   {\n");
	printf("|     |  ___|    \\  |\n");
	printf("|     |       ____\\ |\n");
	printf("|     \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|       ____________\n");
	printf("|      /  ___       \\\n");
	printf("|      | |     _____ |\n");
	printf("|      | |___  \\     |\n");
	printf("|      |     |  \\    |                  {\n");
	printf("|      |  ___|    \\  |\n");
	printf("|      |       ____\\ |\n");
	printf("|      \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|        ____________\n");
	printf("|       /  ___       \\\n");
	printf("|       | |     _____ |\n");
	printf("|       | |___  \\     |\n");
	printf("|       |     |  \\    |                 {\n");
	printf("|       |  ___|    \\  |\n");
	printf("|       |       ____\\ |\n");
	printf("|       \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|         ____________\n");
	printf("|        /  ___       \\\n");
	printf("|        | |     _____ |\n");
	printf("|        | |___  \\     |\n");
	printf("|        |     |  \\    |                {\n");
	printf("|        |  ___|    \\  |\n");
	printf("|        |       ____\\ |\n");
	printf("|        \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|          ____________\n");
	printf("|         /  ___       \\\n");
	printf("|         | |     _____ |\n");
	printf("|         | |___  \\     |\n");
	printf("|         |     |  \\    |               {\n");
	printf("|         |  ___|    \\  |\n");
	printf("|         |       ____\\ |\n");
	printf("|         \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|           ____________\n");
	printf("|          /  ___       \\\n");
	printf("|          | |     _____ |\n");
	printf("|          | |___  \\     |\n");
	printf("|          |     |  \\    |              {\n");
	printf("|          |  ___|    \\  |\n");
	printf("|          |       ____\\ |\n");
	printf("|          \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|            ____________\n");
	printf("|           /  ___       \\\n");
	printf("|           | |     _____ |\n");
	printf("|           | |___  \\     |\n");
	printf("|           |     |  \\    |             {\n");
	printf("|           |  ___|    \\  |\n");
	printf("|           |       ____\\ |\n");
	printf("|           \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|             ____________\n");
	printf("|            /  ___       \\\n");
	printf("|            | |     _____ |\n");
	printf("|            | |___  \\     |\n");
	printf("|            |     |  \\    |            {\n");
	printf("|            |  ___|    \\  |\n");
	printf("|            |       ____\\ |\n");
	printf("|            \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|              ____________\n");
	printf("|             /  ___       \\\n");
	printf("|             | |     _____ |\n");
	printf("|             | |___  \\     |\n");
	printf("|             |     |  \\    |           {\n");
	printf("|             |  ___|    \\  |\n");
	printf("|             |       ____\\ |\n");
	printf("|             \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|               ____________\n");
	printf("|              /  ___       \\\n");
	printf("|              | |     _____ |\n");
	printf("|              | |___  \\     |\n");
	printf("|              |     |  \\    |          {\n");
	printf("|              |  ___|    \\  |\n");
	printf("|              |       ____\\ |\n");
	printf("|              \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                ____________\n");
	printf("|               /  ___       \\\n");
	printf("|               | |     _____ |\n");
	printf("|               | |___  \\     |\n");
	printf("|               |     |  \\    |         {\n");
	printf("|               |  ___|    \\  |\n");
	printf("|               |       ____\\ |\n");
	printf("|               \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                 ____________\n");
	printf("|                /  ___       \\\n");
	printf("|                | |     _____ |\n");
	printf("|                | |___  \\     |\n");
	printf("|                |     |  \\    |        {\n");
	printf("|                |  ___|    \\  |\n");
	printf("|                |       ____\\ |\n");
	printf("|                \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                  ____________\n");
	printf("|                 /  ___       \\\n");
	printf("|                 | |     _____ |\n");
	printf("|                 | |___  \\     |\n");
	printf("|                 |     |  \\    |       {\n");
	printf("|                 |  ___|    \\  |\n");
	printf("|                 |       ____\\ |\n");
	printf("|                 \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                   ____________\n");
	printf("|                  /  ___       \\\n");
	printf("|                  | |     _____ |\n");
	printf("|                  | |___  \\     |\n");
	printf("|                  |     |  \\    |      {\n");
	printf("|                  |  ___|    \\  |\n");
	printf("|                  |       ____\\ |\n");
	printf("|                  \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                    ____________\n");
	printf("|                   /  ___       \\\n");
	printf("|                   | |     _____ |\n");
	printf("|                   | |___  \\     |\n");
	printf("|                   |     |  \\    |     {\n");
	printf("|                   |  ___|    \\  |\n");
	printf("|                   |       ____\\ |\n");
	printf("|                   \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                     ____________\n");
	printf("|                    /  ___       \\\n");
	printf("|                    | |     _____ |\n");
	printf("|                    | |___  \\     |\n");
	printf("|                    |     |  \\    |    {\n");
	printf("|                    |  ___|    \\  |\n");
	printf("|                    |       ____\\ |\n");
	printf("|                    \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                      ____________\n");
	printf("|                     /  ___       \\\n");
	printf("|                     | |     _____ |\n");
	printf("|                     | |___  \\     |\n");
	printf("|                     |     |  \\    |   {\n");
	printf("|                     |  ___|    \\  |\n");
	printf("|                     |       ____\\ |\n");
	printf("|                     \\____________/\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);

	Sleep(400);
    system("CLS");
    printf("\n   SOLDIER :  %s   \tSCORE :  %d",nombreSoldado,score);
	printf("\tLIVES :  %d   \tMISILS :  %d\n\n",vidas,misilTotal);
	printf(" -----------------------------------------------------------------------------\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|\n");
	printf("|                      ____________                                 \n");
	printf("|                     /  ___       \\                               \n");
	printf("|                     | |     _____ |                               \n");
	printf("|                     | |___  \\     |                              \n");
	printf("|                     |     |  \\    |   {                          \n");
	printf("|                     |  ___|    \\  |                              \n");
	printf("|                     |       ____\\ |                              \n");
	printf("|                     \\____________/                               \n");
	printf("|                                        \n");
	printf("|                                        \n");
	printf("|                                        \n");
	printf("|                                        \n");
	printf("|                                        \n");
	printf(" -----------------------------------------------------------------------------\n");
    printf("                              | %d - %d | m",metros,metros);
    Beep(990,100);
	Beep(990,75);
	Beep(780,50);
	Beep(990,100);
	Beep(990,75);
	Beep(780,50);
	Beep(990,75);
	Beep(780,50);
	Beep(820,100);
	Beep(930,100);
	Beep(990,200);
	Beep(990,100);
	Beep(990,75);
	Beep(780,50);
	Beep(990,75);
	Beep(780,50);
	Beep(820,100);
	Beep(930,100);
	Beep(990,200);
	Beep(990,100);
	Beep(990,75);
	Beep(780,50);
	Beep(990,75);
	Beep(780,50);
	Beep(820,100);
	Beep(930,100);
	Beep(990,200);
	system("cls");
	Beep(725,75 );
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    NO   IMAGE    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    CONNECTING    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   --   --   --   |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  ---  ---  ---  -|\n");
	printf("\t\t\t    |     CONNECTING   |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-  ---  ---  ---  |\n");
	printf("\t\t\t    |      CONNECTING  |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | --   --   --   --|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   ---  ---  ---|\n");
	printf("\t\t\t    |       CONNECTING |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t     ------------------\n");														  
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Beep(975,100);
	Beep(975,150);
	Sleep(700);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(500);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   | O    O   |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(200);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |   O    O |   |\n");
	printf("\t\t\t    |   |    uu    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(600);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |   |__|   |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(500);
	system("CLS");
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |   |__|   |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Well done soldier!! Mision Acomplished\n\n\n");
	Sleep(1800);
	system("cls");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    \\/    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(900);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |     q    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	printf("\n\n\t\t    -- Herr General, Over and out.\n\n\n");
	Sleep(1800);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	Beep(975,150);
	Beep(720, 150);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   ____________   |\n");
	printf("\t\t\t    |  /     pF     \\  |\n");
	printf("\t\t\t    | |--------------| |\n");
	printf("\t\t\t    |   |  O    O  |   |\n");
	printf("\t\t\t    |   |    __    |   |\n");
	printf("\t\t\t    |    \\________/    |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |    NO   IMAGE    |\n");
	printf("\t\t\t    |--  ---  ---  --- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |   --   --   --   |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  ---  ---  ---  -|\n");
	printf("\t\t\t    |   NO   IMAGE     |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |-   --   --   --  |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |-  ---  ---  ---  |\n");
	printf("\t\t\t    |  NO   IMAGE      |\n");
	printf("\t\t\t    |---  ---  ---  ---|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    | --   --   --   --|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |--   --   --   -- |\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |--   ---  ---  ---|\n");
	printf("\t\t\t    | NO   IMAGE       |\n");
	printf("\t\t\t    | ---  ---  ---  --|\n");
	printf("\t\t\t    |                  |\n");
	printf("\t\t\t    |  --   --   --   -|\n");
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	printf("\n\n\n\n\n\n\n");
	printf("\t\t\t     ------------------\n");
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t    |%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c|\n",relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno,relleno);
	printf("\t\t\t     ------------------\n");
	Sleep(400);														  
	system("CLS");
	
	getchar();
}
*/



/*
int main(){
	
	int coordx=78,coordy=20;
	int x,y;
	
	char mundo[coordy][coordx];
	
	for(y=0; y<coordy; y++){
			for(x=0; x<coordx; x++){
				
				if((y>0 || y<coordy-1)){
					mundo[y][0]='|';
				}
				if((y!=0 && x!=0) || (y!=coordy-1 && x!=0)){
					mundo[y][x]=' ';
				}
				if(y==0 || y==coordy-1){
					mundo[y][x]='-';
				}
			}
			
			if((y==0) || (y==coordy-1)){
				mundo[y][0]=' ';				
			}
			
			mundo[0][0]=' ';
			mundo[20][0]=' ';
			mundo[0][x]='-';
			mundo[20][x]='-';	
		}
		
			
			//muestra en pantalla el juego.
		for (y = 0; y < coordy; y ++) {
		    for (x = 0; x < coordx; x ++) {
			    printf("%c",mundo[y][x]);
		    }
			printf("\n");
		}
	system("PAUSE");
}*/
